"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var buclesFor_1 = require("./buclesFor");
var condicionales_1 = require("./condicionales");
var casa = ["Casa", "Coche", "Ciudad", "Cesta"];
var barco = ["Barco", "Barca", "Bicicleta", "Balon", "Bisiesto", "Brasil"];
var pais = ["Venezuela", "Veneno", "Voltaje"];
console.log((0, condicionales_1.isEven)((0, buclesFor_1.add)(casa)));
console.log((0, condicionales_1.isEven)((0, buclesFor_1.add)(barco)));
console.log((0, condicionales_1.isEven)((0, buclesFor_1.add)(pais)));
